### ISSUE TITLE
Missing requests module

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jinaai-py#10]
Running this code:

```python
from jinaai import JinaAI

image_url = 'https://images.pexels.com/photos/2529172/pexels-photo-2529172.jpeg'

jinaai = JinaAI(
        secrets = {'scenex': 'moCo8WZeC1gyc0sOKpei:f4d0efecd97f460549a19854a3f3005bab15ab7ce3c2deaaaccf794a20afc4fa'}
        )

output = jinaai.describe(
        input=image_url,
        options={
            'features': 'question_answer',
            'question': 'what\'s in this image?'
            }
        )
```

Throws this error:

```text
Traceback (most recent call last):
  File "/mnt/data/work/sandbox/jinaai-py/visual-qa.py", line 1, in <module>
    from jinaai import JinaAI
  File "/mnt/data/work/sandbox/jinaai-py/env/lib/python3.11/site-packages/jinaai/__init__.py", line 1, in <module>
    from .clients.SceneXClient import SceneXClient
  File "/mnt/data/work/sandbox/jinaai-py/env/lib/python3.11/site-packages/jinaai/clients/SceneXClient.py", line 1, in <module>
    from .HTTPClient import HTTPClient
  File "/mnt/data/work/sandbox/jinaai-py/env/lib/python3.11/site-packages/jinaai/clients/HTTPClient.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Running Python 3.11

**Comment by redjson** [comment]
fixed in jinaai 0.2.1
